hotfix/LW-3. Mailer setup. Fix mailer on dev and prod
itechart-warehouse/backend pull request #57
Opened 2022-05-16 16:09 UTC by MonkeyKingBar-bit

2022-05-17 12:51 UTC, Laranto-spb approved these changes

2022-05-17 13:23 UTC, NDragneelL9 approved these changes

2022-05-17 13:42 UTC, Lonely-fr approved these changes

2022-05-17 14:20 UTC, alllpim approved these changes

2022-05-17 19:20 UTC, helmy-er approved these changes

2022-05-18 07:37 UTC, kel-ln requested changes

2022-05-18 07:37 UTC, kel-ln commented on Gemfile
> +gem 'letter_opener', group: :development
почему не добавить уже в объявленную группу development ?

2022-05-18 07:37 UTC, kel-ln commented on config/environments/production.rb
> +  config.action_mailer.default_url_options = { host: 'https://react-warehouse-app.herokuapp.com/home', port: 3000 }
в случае используются только http 80 и https 443 
в данном случае прописан порт 3000   https://react-warehouse-app.herokuapp.com/home:3000  
нужно указывать только значение host  https://react-warehouse-app.herokuapp.com
и вынести это значение в файл с настройками ( credentials или .env )

2022-05-20 11:23 UTC, kel-ln approved these changes

2022-05-20 15:53 UTC, merged