Feature_lw_1_refactoring_of_routes.fix routes
itechart-warehouse/backend pull request #63
Opened 2022-05-18 14:20 UTC by helmy-er

2022-05-19 11:34 UTC, NDragneelL9 approved these changes

2022-05-19 12:03 UTC, alllpim approved these changes

2022-05-19 13:03 UTC, MonkeyKingBar-bit approved these changes

2022-05-19 16:19 UTC, Laranto-spb approved these changes

2022-05-20 08:06 UTC, Lonely-fr approved these changes

2022-05-20 11:21 UTC, kel-ln requested changes

2022-05-20 11:21 UTC, kel-ln commented on config/routes.rb
> +  resources :company, only: :index do
было   get 'companies', to: 'company#index'
стало   get 'company', to: 'company#index'

куда потерялся экшен show ?

2022-05-20 11:21 UTC, kel-ln commented on config/routes.rb
> +  resources :user, only: :show do
было   get 'users/:id', to: 'user#show'
стало  get 'user/:id', to: 'user#show'

2022-05-20 11:21 UTC, kel-ln commented on config/routes.rb
> +  resources :consignment, except: %i[destroy show create]
экшен update ?

2022-05-20 11:21 UTC, kel-ln commented on config/routes.rb
> +  resources :warehouse, except: %i[destroy update] do
экшен index и create ?

2022-05-20 11:21 UTC, kel-ln commented on config/routes.rb
> +  resources :reports, only: %i[index create] do
откуда эти экшены в роутинге их не было

2022-05-20 11:21 UTC, kel-ln commented on config/routes.rb
> +  scope 'warehouse-consignments' do
почему бы не завернуть в ресурс ?

resources :consignment, path: "warehouse-consignments", only: %i[index show] do 
   collection do 
     ....

2022-05-20 13:20 UTC, merged