Feature/LW-13-Recover-password
itechart-warehouse/backend pull request #66
Opened 2022-05-24 13:14 UTC by NDragneelL9

2022-05-24 14:39 UTC, Laranto-spb approved these changes

2022-05-25 10:01 UTC, alllpim approved these changes

2022-05-25 11:11 UTC, kel-ln requested changes
1. название ветки 
2. добавить тесты на этот контроллер

2022-05-25 11:11 UTC, kel-ln commented on config/routes.rb
> -             },
почему эти пути убраны ? 
jwt их отслеживает

2022-05-25 11:11 UTC, kel-ln commented on app/controllers/passwords_controller.rb
> +    if resource && resource.update!(password: params[:password])
resource.reset_password(resource_params[:password], resource_params[:password_confirmation])

2022-05-25 16:25 UTC, NDragneelL9 commented on config/routes.rb
> -             },
поменял настройки jwt на отслеживание дефолтных рутов

2022-05-31 07:24 UTC, MonkeyKingBar-bit approved these changes

2022-05-31 07:35 UTC, kel-ln approved these changes

2022-05-31 08:22 UTC, Lonely-fr approved these changes

2022-06-01 10:06 UTC, helmy-er approved these changes

2022-06-07 12:49 UTC, merged