Feature/lw 7 pagination
itechart-warehouse/backend pull request #71
Opened 2022-05-30 11:11 UTC by helmy-er

2022-05-31 07:27 UTC, kel-ln requested changes
те же ошибки что и на проекте trucking
1) параметры страницы не должны быть обязательными
2) отсчет должен быть с 1 страницы

2022-05-31 07:27 UTC, kel-ln commented on app/models/warehouse_audit.rb
>    end
код удален ?

2022-05-31 14:28 UTC, NDragneelL9 commented on .env.example
> +sys_admin_token=Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNjUzNjQ1OTQ2LCJleHAiOjE2NTM3MzIzNDYsImp0aSI6ImIzNjY0NGIyLWNkYjItNGNhNC04M2VlLTljODk3ZDYyZjJiMyJ9.el
in .env.example we should show only key names, not values

2022-05-31 14:28 UTC, NDragneelL9 commented on spec/requests/companies_spec.rb
> +      print(response.body)
remove prints?

2022-05-31 14:28 UTC, NDragneelL9 commented on spec/requests/consignments_spec.rb
> +      header={'Authorization': ENV["sys_admin_token"]}
whats the point of sign in as created user in test and using sys_admin jwt token? we probably need to use jwt token which new user got after signing in

2022-06-01 10:45 UTC, NDragneelL9 commented on config/database.yml
> +  database: backend_test
wrong database

2022-06-03 12:00 UTC, NDragneelL9 approved these changes

2022-06-06 10:53 UTC, alllpim approved these changes

2022-06-06 12:34 UTC, kel-ln requested changes

2022-06-06 12:34 UTC, kel-ln commented on app/controllers/company_controller.rb
> +  end
что этот метод делает ?

2022-06-06 12:34 UTC, kel-ln commented on app/controllers/company_controller.rb
>      end
companies, meta = if ability_system?
      paginate_collection(Company.all)
    else
      paginate_collection(Company.where(id: @current_user.company_id))
    end

2022-06-06 12:34 UTC, kel-ln commented on app/controllers/company_controller.rb
> +    render json: { companies: companies, company_count: company_count }
```suggestion
    render json: { companies: companies, company_count: meta[:total_count] }
```

2022-06-06 12:34 UTC, kel-ln commented on app/controllers/concerns/paginatable.rb
> +    end
неправильный расчет страниц

2022-06-06 12:34 UTC, kel-ln commented on app/controllers/consignment_controller.rb
> +                          end
у тебя метод возвращает массив присваивай сразу 2 переменным

2022-06-06 14:16 UTC, NDragneelL9 commented
Пожалуйста, после того как исправляете какие-либо замечания в ПРе, нажимайте кнопку Resolve conversation, чтобы было проще делать ревью

2022-06-07 08:28 UTC, kel-ln approved these changes

2022-06-07 08:28 UTC, kel-ln commented on app/serializers/good_serializer.rb
> +    object.consignment.warehouse_id ? Warehouse.find(object.consignment.warehouse_id) : ''
```suggestion
    object.consignment&.warehouse || ''
```

2022-06-07 09:55 UTC, Lonely-fr approved these changes

2022-06-07 13:01 UTC, merged