Feature/lw 19 sidekiq
itechart-warehouse/backend pull request #73
Opened 2022-06-06 14:20 UTC by NDragneelL9

Right now we need to run sidekiq manually. In future we gonna put everything in docker container.

2022-06-07 08:51 UTC, kel-ln requested changes
нужно вынести в отдельный namespace
если получится закрыть роут  только для пользователя с правами админа

2022-06-07 08:51 UTC, kel-ln commented on Gemfile
> +gem 'sidekiq'
нужен еще 
gem "redis-namespace"

2022-06-07 08:51 UTC, kel-ln commented on config/initializers/sidekiq.rb
> +  config.redis = { url: 'redis://127.0.0.1:6379' }
url нужно вынести в переменную и привязать к ENV

2022-06-09 20:36 UTC, kel-ln approved these changes

2022-06-09 20:36 UTC, kel-ln commented on app/assets/config/manifest.js
> +//= link_directory ../stylesheets .css
для чего ?

2022-06-10 07:59 UTC, Lonely-fr approved these changes

2022-06-10 09:50 UTC, NDragneelL9 commented on app/assets/config/manifest.js
> +//= link_directory ../stylesheets .css
Когда подключали страницу sidekiqa, ты посоветовал раскоментить require "sprockets/railtie", после перезагрузки вроде выкинуло ошибку, и для её фикса нужно было сгенерить дефолтные файлы.

2022-06-10 11:38 UTC, helmy-er approved these changes

2022-06-10 23:00 UTC, MonkeyKingBar-bit approved these changes

2022-06-13 12:21 UTC, merged