Feature/lw-11-searching backend
itechart-warehouse/backend pull request #75
Opened 2022-06-08 12:18 UTC by helmy-er

2022-06-08 13:39 UTC, NDragneelL9 approved these changes

2022-06-09 20:43 UTC, kel-ln requested changes

2022-06-09 20:43 UTC, kel-ln commented on app/controllers/company_controller.rb
> +    end
```suggestion
    query = companies_query
    query = query.search(params[:search]) if !params[:search].blank?
    companies, meta = paginate_collection(query)
     render json: { companies: companies, company_count: meta[:total_count] }
    end
```

2022-06-09 20:43 UTC, kel-ln commented on app/controllers/consignment_controller.rb
> +      render json: consignments_count, status: :ok
пример выше

2022-06-09 20:43 UTC, kel-ln commented on app/controllers/passwords_controller.rb
>    end
изменения из стороннего ПР ?

2022-06-09 20:43 UTC, kel-ln commented on app/controllers/user_controller.rb
> +    end
как в примере выше

2022-06-09 20:43 UTC, kel-ln commented on app/controllers/warehouse_controller.rb
> +    end
как в примере выше

2022-06-09 20:43 UTC, kel-ln commented on app/models/company.rb
> +  scope :search,->(search_data){where("name ilike '#{search_data}%'",)}
название не отражает ничего нужно более подходящее

2022-06-09 20:43 UTC, kel-ln commented on app/models/consignment.rb
>  end
что будет если значение search_date не будет содержать пробел? или будет содержать 2 или больше пробелов ?

2022-06-09 20:43 UTC, kel-ln commented on app/models/user.rb
> +
тот же самое

2022-06-09 20:43 UTC, kel-ln commented on app/models/warehouse.rb
> +  scope :search,->(search_data){where("name ilike '#{search_data}%'")}
поменять название

2022-06-10 09:39 UTC, helmy-er commented on app/controllers/passwords_controller.rb
>    end
нет , исправления рубокопа

2022-06-10 23:02 UTC, MonkeyKingBar-bit approved these changes

2022-06-13 13:17 UTC, kel-ln approved these changes

2022-06-13 13:17 UTC, kel-ln commented on app/controllers/user_controller.rb
> +      Company.find(@current_user.company_id).users
```suggestion
      User.where( company_id: @current_user.company_id)
```

2022-06-13 13:17 UTC, kel-ln commented on app/controllers/user_controller.rb
> +      Warehouse.find(@current_user.warehouse_id).users
```suggestion
      User.where(warehouse_id: @current_user.warehouse_id)
```

2022-06-15 00:18 UTC, Lonely-fr approved these changes

2022-06-16 11:09 UTC, alllpim approved these changes

2022-06-20 08:24 UTC, merged