Feature/w-28-docker
itechart-warehouse/backend pull request #78
Opened 2022-06-16 13:54 UTC by helmy-er

Папка с фронтом и бэком должна находиться в одной директории ,пример : обе папки находятся на диске Д.Для запуска на линуксе make build ,на винде make build -f makefile.windows  ,все команды прописываем на проекте с бэком

2022-06-16 14:02 UTC, helmy-er commented
Папка с фронтом и бэком должна находиться в одной директории ,пример : обе папки находятся на диске Д.

2022-06-17 10:54 UTC, NDragneelL9 commented on config/database.yml
> +  username: trucking
думаю у преокта warehouse не стоит называть юзера базы данных trucking

2022-06-17 10:54 UTC, NDragneelL9 commented on config/database.yml
> +  password: <%= ENV['TRUCKING_DATABASE_PASSWORD'] %>
тут тоже думаю название переменной можно поменять

2022-06-17 10:54 UTC, NDragneelL9 commented on db/schema.rb
> -
а куда таблица пропала?

2022-06-17 10:54 UTC, NDragneelL9 commented on dip.yml
> +
по-хорошему добавить ещё сюда и sidekiq, мб стоит сделать ребейз от дева (если сайдкик уже там) или с моей таски с сайдкиком, ибо все равно приедтся это делать

2022-06-22 13:00 UTC, NDragneelL9 commented on Makefile
> +	@dip rails db:rollback
Эти команда я так понял не нужны, (команда provision в целом тоже). Насколько я понял, через Makefile нам нужно только делать билд проекта и все

2022-06-22 13:00 UTC, NDragneelL9 commented on entrypoints/docker-entrypoint.sh
> +exec "$@"
А зачем тебе этот файл?

2022-06-22 13:09 UTC, helmy-er commented on Makefile
> +	@dip rails db:rollback
Да команды не обязательные,но просто экономят время

2022-06-23 08:17 UTC, kel-ln requested changes

2022-06-23 08:17 UTC, kel-ln commented on .dockerdev/Dockerfile
> +# Application dependencies
ARG BUNDLER_VERSION

2022-06-23 08:17 UTC, kel-ln commented on .dockerdev/Dockerfile
> +  gem install bundler
```suggestion
  gem install bundler:$BUNDLER_VERSION
```

2022-06-23 08:17 UTC, kel-ln commented on .dockerdev/Dockerfile
> +ARG YARN_VERSION
yarn нужен ? не вижу чтоб он устанавливался

2022-06-23 08:17 UTC, kel-ln commented on .dockerdev/Dockerfile
> +
RUN curl -sL https://deb.nodesource.com/setup_$NODE_MAJOR.x | bash -

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list

2022-06-23 08:17 UTC, kel-ln commented on .dockerdev/Dockerfile
> +  && truncate -s 0 /var/log/*log
```suggestion
RUN apt-get update  &&  DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  postgresql-client-$PG_MAJOR \
  nodejs \
  yarn=$YARN_VERSION-1 \
  $(grep -Ev '^\s*#' /tmp/Aptfile | xargs) \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && truncate -s 0 /var/log/*log
```

2022-06-23 08:17 UTC, kel-ln commented on .dockerdev/Dockerfile
> +  && truncate -s 0 /var/log/*log
перенеси выше до команды RUN apt-get

2022-06-23 08:17 UTC, kel-ln commented on .dockerdev/Aptfile
> +postgresql-client
```suggestion
vim
gnupg2
curl
less
git
build-essential
libpq-dev
```

2022-06-23 08:17 UTC, kel-ln commented on .dockerdev/compose.yml
> +    - /backend/tmp/pids
?

2022-06-23 08:17 UTC, kel-ln commented on Makefile
> +	@dip rails db:rollback
тут нужны всего две команды install для бека и фронта
что то такое должно быть

install: deps
  dip provision
  lefthook install
deps:
  @ which dip &> /dev/null || gem install dip
  @ which lefthook &> /dev/null || gem install lefthook

и для реакта что то такое

react:
	rm -rf public/assets/react
	dip react_build

2022-06-23 08:17 UTC, kel-ln commented on dip.yml
> +    command:  rails
```suggestion
    service: runner
    command: bundle exec rails
```

2022-06-23 08:17 UTC, kel-ln commented on dip.yml
> +    command: psql -h postgres -U postgres
```suggestion
  psql:
    description: Run Postgres psql console
    service: postgres
    command: psql -h postgres -U postgres
```

2022-06-23 08:17 UTC, kel-ln commented on dip.yml
> +
добавить для rubocop, redis-cli,  yarn и билда ректа

2022-06-23 08:17 UTC, kel-ln commented on dip.yml
> +  - dip compose up -d
убрать, добавить команды билда фронта

2022-06-23 08:17 UTC, kel-ln commented on entrypoints/docker-entrypoint.sh
> +exec "$@"
файл не нужен

2022-06-23 08:17 UTC, kel-ln commented on lefthook.yml
> +      run: bundle exec rubocop --force-exclusion -A {staged_files}
```suggestion
pre-commit:
  commands:
    rubocop:
      files: git diff --name-only --staged
      glob: "*.rb"
      run: dip rubocop --force-exclusion -a {files} && git add {files}
```

2022-06-23 09:55 UTC, helmy-er commented on .dockerdev/Dockerfile
> +
нет необходимости так как фронтовая часть находится в докерфайле фронта

2022-06-23 10:00 UTC, helmy-er commented on .dockerdev/compose.yml
> +    - /backend/tmp/pids
нужно чтобы не было конфликтов с пид файлом

2022-06-23 10:04 UTC, helmy-er commented on .dockerdev/Dockerfile
> +  && truncate -s 0 /var/log/*log
возникает ошибка о необходимости курла который устанавливается в apt-get

2022-06-24 06:51 UTC, kel-ln requested changes

2022-06-24 06:51 UTC, kel-ln commented on .dockerdev/Dockerfile
> +  && truncate -s 0 /var/log/*log
где идет установка postgre пакета ?

2022-06-24 06:51 UTC, kel-ln commented on Makefile
> +	@bundle install
зачем ? в dip provision есть эта команда

2022-06-24 08:00 UTC, Lonely-fr commented
![image](https://user-images.githubusercontent.com/70891250/175490985-ada33bd2-3cc2-4e6e-941d-3d7aa0165fe6.png)
Tested Win 10 Pro

2022-06-24 08:00 UTC, Lonely-fr approved these changes

2022-06-24 09:40 UTC, kel-ln approved these changes

2022-06-24 09:54 UTC, MonkeyKingBar-bit approved these changes

2022-06-25 11:05 UTC, Laranto-spb approved these changes

2022-06-27 10:18 UTC, closed without merging